name: Node.js Rss Spider

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: run node index.js # 
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
        run: npm install && npm run build
    
      - name: Generate pages
        run: ls -R data/
        
      - name: Commit files
        run: |
         git config --local user.email "380863274@qq.com"
         git config --local user.name "jackieli123723"
         git pull
         git add data/*
         git commit -m "update data"
      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main  
